/* Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ */
package cn.zhuatech.clm.service;
import cn.zhuatech.clm.common.BusinessException; import cn.zhuatech.clm.dto.ClmDto.*; import cn.zhuatech.clm.model.*; import cn.zhuatech.clm.repository.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @Transactional(readOnly=true) public class ClmService {
    private final ContractReviewRepository orders; private final ApprovalRecordRepository reports; private final ClauseTemplateRepository clauseTemplate; private final ObligationAlertRepository obligationAlerts; private final CurrentUserService current;
    public ClmService(ContractReviewRepository orders,ApprovalRecordRepository reports,ClauseTemplateRepository clauseTemplate,ObligationAlertRepository obligationAlerts,CurrentUserService current){this.orders=orders;this.reports=reports;this.clauseTemplate=clauseTemplate;this.obligationAlerts=obligationAlerts;this.current=current;}
    public Dashboard shopfloorDashboard(){String center=current.get().getContractPortfolioCode();List<ContractReview> list=center==null?orders.findAllByOrderByDueDateAsc():orders.findByContractPortfolioCodeOrderByDueDateAsc(center);return dashboard(list);}
    public Dashboard adminDashboard(){return dashboard(orders.findAllByOrderByDueDateAsc());}
    public List<ContractReviewView> contractReviews(){return orders.findAllByOrderByDueDateAsc().stream().map(this::view).toList();}
    @Transactional public ReportResult report(Long id,ReportRequest request){ContractReview order=orders.findById(id).orElseThrow(()->new BusinessException("合同审查不存在"));if(order.getStatus()==ContractReview.Status.COMPLETED)throw new BusinessException("已完成任务不能继续反馈");if(order.getCompletedQty()+request.goodQty()>order.getPlannedQty())throw new BusinessException("完成数量不能超过任务剩余数量");order.report(request.goodQty(),request.defectQty());reports.save(new ApprovalRecord(order,request.operationName(),request.goodQty(),request.defectQty(),current.get().getFullName(),request.remark()));return new ReportResult(order.getOrderNo(),order.getCompletedQty(),order.getDefectQty(),progress(order),order.getStatus().name());}
    private Dashboard dashboard(List<ContractReview> list){int planned=list.stream().mapToInt(ContractReview::getPlannedQty).sum(),done=list.stream().mapToInt(ContractReview::getCompletedQty).sum(),defects=list.stream().mapToInt(ContractReview::getDefectQty).sum();int rate=planned==0?0:Math.round(done*100f/planned);List<Metric> metrics=List.of(new Metric("今日审查",String.format("%,d",planned),list.size()+" 张合同审查","blue"),new Metric("审查完成率",rate+"%",String.format("%,d / %,d",done,planned),"green"),new Metric("结果合同风控率",String.format("%.1f%%",done+defects==0?100d:done*100d/(done+defects)),defects+" 项异常","warn"),new Metric("条款模板异常",clauseTemplate.countByStatus(ClauseTemplate.Status.ALARM)+"",obligationAlerts.countByResult(ObligationAlert.Result.PENDING)+" 项待复核","red"));return new Dashboard(metrics,list.stream().map(this::view).toList(),clauseTemplate.findAllByOrderByCodeAsc().stream().map(e->new ControlView(e.getCode(),e.getName(),e.getContractPortfolio().getName(),e.getStatus().name(),e.getOee(),e.getLastHeartbeat())).toList(),obligationAlerts.findTop10ByOrderByIdDesc().stream().map(i->new ObligationAlertView(i.getObligationAlertNo(),i.getContractReview().getOrderNo(),i.getContractReview().getProductName(),i.getObligationAlertType(),i.getObligationAlertQty(),i.getDefectQty(),i.getResult().name(),i.getInspector())).toList());}
    private ContractReviewView view(ContractReview o){return new ContractReviewView(o.getId(),o.getOrderNo(),o.getProductCode(),o.getProductName(),o.getContractPortfolio().getName(),o.getContractPortfolio().getWorkshop(),o.getPlannedQty(),o.getCompletedQty(),o.getDefectQty(),o.getDueDate(),o.getStatus().name(),o.getBatchNo(),progress(o));}
    private int progress(ContractReview o){return o.getPlannedQty()==0?0:Math.min(100,Math.round(o.getCompletedQty()*100f/o.getPlannedQty()));}
}
